---
- name: "Install PAM."
  apt: name={{ item }} state=present
  with_items:
  - libpam-pwdfile
  - python-passlib

- name: Setup PAM
  copy:
    src: ../configs/openvpn.pam
    dest: "/etc/pam.d/openvpn"

- name: Configure server
  template: src=server.j2 dest={{openvpn_etcdir}}/server.conf
  notify: [openvpn restart]

- name: Ensure openvpn key dir has the right permission
  file: path={{openvpn_keydir}} state=directory mode=0700 owner={{openvpn_user}}
